SELECT
  TRIM(CAST(customer_code AS VARCHAR)) AS cl_cc,
  regexp_replace(TRIM(mobile_phone), '\s+', '') AS cl_phone,
  regexp_replace(TRIM(identification_number), '\s+', '') AS cl_vin,
  LOWER(TRIM(email)) AS cl_email,
  regexp_replace(
    regexp_replace(
      regexp_replace(
        regexp_replace(
          regexp_replace(
            regexp_replace(
              regexp_replace(
                regexp_replace(
                  LOWER(TRIM(customer_name)),
                  '\s+',
                  ' '
                ),
                '[áàảãạăắằẳẵặâấầẩẫậ]',
                'a'
              ),
              '[éèẻẽẹêếềểễệ]',
              'e'
            ),
            '[íìỉĩị]',
            'i'
          ),
          '[óòỏõọôốồổỗộơớờởỡợ]',
          'o'
        ),
        '[úùủũụưứừửữự]',
        'u'
      ),
      '[ýỳỷỹỵ]',
      'y'
    ),
    'đ',
    'd'
  ) AS cl_customer_name,
  CONCAT(
  regexp_replace(
    regexp_replace(
      regexp_replace(
        regexp_replace(
          regexp_replace(
            regexp_replace(
              regexp_replace(
                regexp_replace(
                  LOWER(TRIM(city)),
                  '\s+',
                  ' '
                ),
                '[áàảãạăắằẳẵặâấầẩẫậ]',
                'a'
              ),
              '[éèẻẽẹêếềểễệ]',
              'e'
            ),
            '[íìỉĩị]',
            'i'
          ),
          '[óòỏõọôốồổỗộơớờởỡợ]',
          'o'
        ),
        '[úùủũụưứừửữự]',
        'u'
      ),
      '[ýỳỷỹỵ]',
      'y'
    ),
    'đ',
    'd'
  ),
  ';',
  regexp_replace(
    regexp_replace(
      regexp_replace(
        regexp_replace(
          regexp_replace(
            regexp_replace(
              regexp_replace(
                regexp_replace(
                  LOWER(TRIM(district)),
                  '\s+',
                  ' '
                ),
                '[áàảãạăắằẳẵặâấầẩẫậ]',
                'a'
              ),
              '[éèẻẽẹêếềểễệ]',
              'e'
            ),
            '[íìỉĩị]',
            'i'
          ),
          '[óòỏõọôốồổỗộơớờởỡợ]',
          'o'
        ),
        '[úùủũụưứừửữự]',
        'u'
      ),
      '[ýỳỷỹỵ]',
      'y'
    ),
    'đ',
    'd'
  ),
  ';',
  regexp_replace(
    regexp_replace(
      regexp_replace(
        regexp_replace(
          regexp_replace(
            regexp_replace(
              regexp_replace(
                regexp_replace(
                  LOWER(TRIM(customer_address)),
                  '\s+',
                  ' '
                ),
                '[áàảãạăắằẳẵặâấầẩẫậ]',
                'a'
              ),
              '[éèẻẽẹêếềểễệ]',
              'e'
            ),
            '[íìỉĩị]',
            'i'
          ),
          '[óòỏõọôốồổỗộơớờởỡợ]',
          'o'
        ),
        '[úùủũụưứừửữự]',
        'u'
      ),
      '[ýỳỷỹỵ]',
      'y'
    ),
    'đ',
    'd'
  )) AS cl_full_address,
  regexp_replace(
    regexp_replace(
      regexp_replace(
        regexp_replace(
          regexp_replace(
            regexp_replace(
              regexp_replace(
                regexp_replace(
                  LOWER(TRIM(city)),
                  '\s+',
                  ' '
                ),
                '[áàảãạăắằẳẵặâấầẩẫậ]',
                'a'
              ),
              '[éèẻẽẹêếềểễệ]',
              'e'
            ),
            '[íìỉĩị]',
            'i'
          ),
          '[óòỏõọôốồổỗộơớờởỡợ]',
          'o'
        ),
        '[úùủũụưứừửữự]',
        'u'
      ),
      '[ýỳỷỹỵ]',
      'y'
    ),
    'đ',
    'd'
  ) AS cl_city,
  *
FROM
  ${db}.${source_tbl}