in:
  type: amplitude
  api_key: ${secret:amplitude.api_key}
  secret_key: ${secret:amplitude.secret_key}
  start_time: ${amplitude.start_time}
out: {}
exec: {}
filters:
- type: rename
  rules:
  - rule: upper_to_lower
  - rule: character_types
    pass_types: ["a-z", "0-9"]
    pass_characters: "_"
    replace: "_"
  - rule: first_character_types
    pass_types: ["a-z"]
    pass_characters: "_"
    prefix: "_"
  - rule: unique_number_suffix
    max_length: 128
- type: add_time
  to_column: {name: time}
  from_value: {mode: upload_time}
