in:
  type: sftp_v2
  host: ${secret:sftp.host}
  port: ${secret:sftp.port}
  auth_method: key_pair
  #auth_method: password
  user: ${secret:sftp.user}
  secret_key_file: {"content": "${secret:sftp.secret_key_file}"}
  secret_key_passphrase: ${secret:sftp.secret_key_passphrase}
  user_directory_is_root: ${sftp.user_directory_is_root}
  timeout: ${sftp.timeout}
  path_prefix: "/path/file_${moment(session_time).format("YYYYMMDD")}.csv"
  parser:
    charset: UTF-8
    newline: LF
    type: csv
    delimiter: ","
    quote: "\""
    escape: "\""
    trim_if_not_quoted: false
    skip_header_lines: 1
    allow_extra_columns: false
    allow_optional_columns: false
    columns:
    - {name: time, type: long}
    - {name: id, type: long}
    - {name: name, type: string}
    - {name: category, type: string}
out: {}
